# Site settings
title: Jekyllサンプルブログ
description: "Jekyllでのブログ作成サンプルです"
baseurl: ""
url: "http://sample-blog.enogineer.com"
twitter_username: haracane
github_username:  haracane

# Build settings
markdown: kramdown
permalink: pretty
